language: cpp

dist: trusty
sudo: required

git:
  depth: 10

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/prepare.sh & ./util/osx/prepare.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/prepare.sh & sudo ./util/ubuntu/prepare.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/build.sh & ./util/osx/build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/build.sh & ./util/ubuntu/build.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "piWcuto+dUFTh3FLZO8TF9Ynmd37oH3Fz58uleaP4nymGy783Lg3TqmZ0QEd5tDe1zY5quGEUpRRdusht3lUfUHWYCNLedRgWdRxGYZSC0exchUZfmE8CyEnFR8GNGOVhhhkq5smQ9LvrHSQd9aReww+TXmgfRnWkxLLNoH63zXG0EBpvLfT8d7TRGn7z9Q6iIMA6uy0374bPYPNdYDfn1FU0ic6ULQwhWgHIRc1Q2WM/AQRjmKsbT1T/SP07Pjc999VWUMLo4UL9rSKMLt4RRm5TOEYKJDxVtV3tfo3f/glqGOxNuLOwk5FVGfXmmXd+DCvewQHjDwsBrx/1BDpkAVtGvDUxUZ7jUZFFrvrOTZ/tLjXBjqavNkyerHEdZrhsRzFKLkJNDercOa4GKdwI3rX1eoeXwA2dzpBhT08YnaTmkf7IYyfrcHivcnZwbRNLwUbaKfW5qHUrLNQJqr6VY6PnW6OgdC8lefecBOHuj/5E9GLcUxPFzcbGw28rJisVefFCVThqe6qE0L/cLTOk7+qiD+KqapdNx1gYIILMOTTJrf0KS8V732Wk//b8yS9PzpQ/+EyGpoyh2GPWNNpg87mrmxvsiZlkcQimsJbk0Y6et0E7Jbf1TB34u7zuhfcm5yXP2DKkIVmqDhf4VpCo1MMBLpZ169W7ehQT6lN8HY="
    file_glob: true
    file: "QtcMarkview-*.tar.gz"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: change
